// packages/react/src/viewer.tsx
import React, { useMemo, useEffect, useRef, FC } from 'react'
import * as bytemd from 'bytemd'

export interface ViewerProps extends bytemd.ViewerProps {}

export const Viewer: FC<ViewerProps> = ({
  value,
  sanitize,
  plugins,
  remarkRehype,
}) => {
  const elRef = useRef<HTMLDivElement>(null)
  const file = useMemo(() => {
    try {
      return bytemd
        .getProcessor({ sanitize, plugins, remarkRehype })
        .processSync(value)
    } catch (err) {
      console.error(err)
    }
  }, [value, sanitize, plugins, remarkRehype])

  useEffect(() => {
    const markdownBody = elRef.current
    if (!markdownBody || !file) return

    const cbs = plugins?.map(({ viewerEffect }) =>
      viewerEffect?.({ markdownBody, file })
    )
    return () => {
      cbs?.forEach((cb) => cb && cb())
    }
  }, [file, plugins])

  return (
    <div
      onClick={(e) => {
        const $ = e.target as HTMLElement
        if ($.tagName !== 'A') return

        const href = $.getAttribute('href')
        if (!href?.startsWith('#')) return

        elRef.current
          ?.querySelector('#user-content-' + href.slice(1))
          ?.scrollIntoView()
      }}
      ref={elRef}
      className="markdown-body"
      dangerouslySetInnerHTML={{ __html: file?.toString() ?? '' }}
    ></div>
  )
}

// packages/vue/src/viewer.vue
<template>
  <div class="markdown-body" v-html="file" @click="handleClick($event)"></div>
</template>

<script>
import { getProcessor } from 'bytemd'

export default {
  props: ['value', 'plugins', 'sanitize', 'remarkRehype'],
  computed: {
    file() {
      try {
        return getProcessor(this.$props).processSync(this.value)
      } catch (err) {
        console.error(err)
      }
    },
    needUpdate() {
      return [this.file, this.plugins, this.sanitize, this.remarkRehype]
    },
  },
  watch: {
    needUpdate: {
      handler(val) {
        this.off()
        this.$nextTick(() => {
          this.on()
        })
      },
      deep: true,
    },
  },
  mounted() {
    this.on()
  },
  beforeDestroy() {
    this.off()
  },
  methods: {
    on() {
      if (this.plugins && this.file) {
        this.cbs = this.plugins.map(
          ({ viewerEffect }) =>
            viewerEffect &&
            viewerEffect({ markdownBody: this.$el, file: this.file })
        )
      }
    },
    off() {
      if (this.cbs) {
        this.cbs.forEach((cb) => cb && cb())
      }
    },
    handleClick(e) {
      const $ = e.target
      if ($.tagName !== 'A') return

      const href = $.getAttribute('href')
      if (!href || !href.startsWith('#')) return

      const dest = this.$el.querySelector('#user-content-' + href.slice(1))
      if (dest) dest.scrollIntoView()
    },
  },
}
</script>
