// packages/bytemd-react/src/index.tsx
import * as React from 'react';
import * as bytemd from 'bytemd';

class SvelteComponent extends React.Component<any> {
  container: any;
  instance: any;
  div: any;

  constructor(props: any) {
    super(props);

    this.container = React.createRef();
    this.instance = null;
    this.div = React.createElement('div', { ref: this.container });
  }

  componentDidMount() {
    const { this: Constructor, ...props } = this.props;

    this.instance = new Constructor({
      target: this.container.current,
      props,
    });
    this.instance.$on('change', (e: any) => {
      if (this.props.onChange) {
        this.props.onChange(e.detail.value);
      }
    });
  }

  componentDidUpdate() {
    this.instance.$set(this.props);
  }

  componentWillUnmount() {
    this.instance.$destroy();
  }

  render() {
    return this.div;
  }
}

export interface EditorProps extends bytemd.EditorProps {
  onChange?(value: string): void;
}

export const Editor: React.FC<EditorProps> = props => (
  <SvelteComponent this={bytemd.Editor} {...props} />
);

export interface ViewerProps extends bytemd.ViewerProps {}

export const Viewer: React.FC<ViewerProps> = props => (
  <SvelteComponent this={bytemd.Viewer} {...props} />
);

// packages/bytemd/react/src/index.tsx
import React, { RefObject } from 'react';
import * as bytemd from 'bytemd';
import { SvelteComponent } from 'svelte';

class SvelteWrapper<
  P extends Record<string, unknown> = {}
> extends React.Component<
  P & {
    component: typeof SvelteComponent;
    onMount?: (instance: SvelteComponent) => void;
  }
> {
  private container: RefObject<HTMLDivElement> = React.createRef();
  private instance?: SvelteComponent;

  componentDidMount() {
    const { component: Component, onMount } = this.props;

    this.instance = new Component({
      target: this.container.current!,
      props: this.props,
    });

    if (onMount) {
      onMount(this.instance);
    }
  }

  componentDidUpdate() {
    this.instance!.$set(this.props);
  }

  componentWillUnmount() {
    this.instance!.$destroy();
  }

  render() {
    return <div ref={this.container} />;
  }
}

export interface EditorProps extends bytemd.EditorProps {
  onChange?(value: string): void;
}

export const Editor: React.FC<EditorProps> = (props) => (
  <SvelteWrapper
    {...props}
    onMount={(instance) => {
      instance.$on('change', (e: any) => {
        if (props.onChange) {
          props.onChange(e.detail.value);
        }
      });
    }}
    component={bytemd.Editor}
  />
);

export interface ViewerProps extends bytemd.ViewerProps {}

export const Viewer: React.FC<ViewerProps> = (props) => (
  <SvelteWrapper {...props} component={bytemd.Viewer} />
);
