// packages/bytemd/vue/src/viewer.vue
<template>
  <div class="markdown-body" v-html="html"></div>
</template>

<script>
import { processMarkdown } from 'bytemd';

export default {
  props: ['value', 'markdownOptions', 'plugins'],
  mounted() {
    if (this.plugins) {
      this.plugins.forEach(({ onMount }) => {
        if (onMount) onMount(this.$el);
      });
    }
  },
  computed: {
    html() {
      return processMarkdown(this.$props);
    },
  },
};
</script>

// packages/bytemd/react/src/viewer.tsx
import React, { useMemo, useEffect, useRef } from 'react';
import * as bytemd from 'bytemd';

export interface ViewerProps extends bytemd.ViewerProps {}

export const Viewer: React.FC<ViewerProps> = ({
  value,
  markdownOptions,
  plugins,
}) => {
  const el = useRef<HTMLDivElement>(null);
  const html = useMemo(
    () => bytemd.processMarkdown({ value, markdownOptions, plugins }),
    [value, markdownOptions, plugins]
  );

  useEffect(() => {
    plugins?.forEach(({ onMount }) => {
      if (onMount && el.current) onMount(el.current);
    });
  }, [html]);

  return (
    <div
      ref={el}
      className="markdown-body"
      dangerouslySetInnerHTML={{ __html: html }}
    ></div>
  );
};
